function Ez = updateTFSFboundEz(Ez_prev, Hx_inc, Hy_inc, tf_region_start, ...
    tf_region_end, dx, dy, dt)

    Ez = Ez_prev;
    e0=8.85418781762e-12;

    % Update Ez TFSF boundaries at xn
    Ez(tf_region_start(1), tf_region_start(2):tf_region_end(2)) = ...
        Ez(tf_region_start(1), tf_region_start(2):tf_region_end(2)) + ...
        dt/(e0*dy)*Hy_inc(tf_region_start(1), tf_region_start(2):tf_region_end(2));

    % Update Ez TFSF boundaries at xp
    Ez(tf_region_end(1), tf_region_start(2):tf_region_end(2)) = ...
            Ez(tf_region_end(1), tf_region_start(2):tf_region_end(2)) - ...
            dt/(e0*dy)*Hy_inc(tf_region_end(1), tf_region_start(2):tf_region_end(2));
    
    % Update Ez TFSF boundaries at yn
    Ez(tf_region_start(1):tf_region_end(1), tf_region_start(2)) = ...
        Ez(tf_region_start(1):tf_region_end(1), tf_region_start(2)) + ...
        dt/(e0*dx)*Hx_inc(tf_region_start(1):tf_region_end(1), tf_region_start(2));

    % Update Ez TFSF boundaries at yp
    Ez(tf_region_start(1):tf_region_end(1), tf_region_end(2)) = ...
        Ez(tf_region_start(1):tf_region_end(1), tf_region_end(2)) - ...
        dt/(e0*dx)*Hx_inc(tf_region_start(1):tf_region_end(1), tf_region_end(2));
end