function [Ex, Ey, Ez] = updateBoundE(Ex_p, Ey_p, Ez_p, Hx_i, Hy_i, Hz_i, ...
    tf_region_start, tf_region_end, dx, dy, dz, dt)

    Ex = Ex_p;
    Ey = Ey_p;
    Ez = Ez_p;

    e0=8.85418781762e-12;

    % Update E TFSF boundaries at xn
    Ey(tf_region_start(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) = ...
        Ey(tf_region_start(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) + ...
        dt/(e0*dy)*Hz_i(tf_region_start(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3));

    Ez(tf_region_start(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) = ...
        Ez(tf_region_start(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) - ...
        dt/(e0*dz)*Hy_i(tf_region_start(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3));

    % Update E TFSF boundaries at xp
    Ey(tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) = ...
        Ey(tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) - ...
        dt/(e0*dy)*Hz_i(tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3));

    Ez(tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) = ...
        Ez(tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3)) + ...
        dt/(e0*dz)*Hy_i(tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3):tf_region_end(3));
    
    % Update E TFSF boundaries at yn
    Ex(tf_region_start(1):tf_region_end(1), tf_region_start(2), tf_region_start(3):tf_region_end(3)) = ...
        Ex(tf_region_start(1):tf_region_end(1), tf_region_start(2), tf_region_start(3):tf_region_end(3)) - ...
        dt/(e0*dx)*Hz_i(tf_region_start(1):tf_region_end(1), tf_region_start(2), tf_region_start(3):tf_region_end(3));

    Ez(tf_region_start(1):tf_region_end(1), tf_region_start(2), tf_region_start(3):tf_region_end(3)) = ...
        Ez(tf_region_start(1):tf_region_end(1), tf_region_start(2), tf_region_start(3):tf_region_end(3)) + ...
        dt/(e0*dz)*Hx_i(tf_region_start(1):tf_region_end(1), tf_region_start(2), tf_region_start(3):tf_region_end(3));

    % Update E TFSF boundaries at yp
    Ex(tf_region_start(1):tf_region_end(1), tf_region_end(2), tf_region_start(3):tf_region_end(3)) = ...
        Ex(tf_region_start(1):tf_region_end(1), tf_region_end(2), tf_region_start(3):tf_region_end(3)) + ...
        dt/(e0*dx)*Hz_i(tf_region_start(1):tf_region_end(1), tf_region_end(2), tf_region_start(3):tf_region_end(3));

    Ez(tf_region_start(1):tf_region_end(1), tf_region_end(2), tf_region_start(3):tf_region_end(3)) = ...
        Ez(tf_region_start(1):tf_region_end(1), tf_region_end(2), tf_region_start(3):tf_region_end(3)) - ...
        dt/(e0*dz)*Hx_i(tf_region_start(1):tf_region_end(1), tf_region_end(2), tf_region_start(3):tf_region_end(3));

    % Update E TFSF boundaries at zn
    Ex(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3)) = ...
        Ex(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3)) + ...
        dt/(e0*dx)*Hy_i(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3));

    Ey(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3)) = ...
        Ey(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3)) - ...
        dt/(e0*dy)*Hx_i(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_start(3));

    % Update E TFSF boundaries at zp
    Ex(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_end(3)) = ...
        Ex(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_end(3)) - ...
        dt/(e0*dx)*Hy_i(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_end(3));

    Ey(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_end(3)) = ...
        Ey(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_end(3)) + ...
        dt/(e0*dy)*Hx_i(tf_region_start(1):tf_region_end(1), tf_region_start(2):tf_region_end(2), tf_region_end(3));


end